# Generated by Django 4.2.7 on 2023-11-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=15, null=True)),
                ('client_surname', models.CharField(blank=True, max_length=15, null=True)),
                ('client_patronymic', models.CharField(blank=True, max_length=15, null=True)),
                ('client_birth', models.DateField(blank=True, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialOrganization',
            fields=[
                ('id_commercial_organization', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=30, null=True)),
                ('tin', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'commercial_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=53, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentForm',
            fields=[
                ('id_establishment_form', models.AutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'establishment_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_address', models.CharField(blank=True, max_length=30, null=True)),
                ('order_status', models.BooleanField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(blank=True, max_length=30, null=True)),
                ('product_size', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id_receipt', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_product_amount', models.SmallIntegerField(blank=True, null=True)),
                ('receipt_product_price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id_sales_point', models.AutoField(primary_key=True, serialize=False)),
                ('sales_point_address', models.CharField(blank=True, max_length=30, null=True)),
                ('sales_point_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sales_point',
                'managed': False,
            },
        ),
    ]
